### ISSUE TITLE
are there any plans to port this to v0.16 or v0.17

### ISSUE THREAD

**Issue by mgiaco** [hamish2014/FreeCAD_assembly2#115]

**Comment by hamish2014** [comment]
Hi mgiaco,

FreeCAD_assembly2 should work in FreeCAD v0.16.
There are no plans at the moment to port to FreeCAD v0.17

Cheers,

**Comment by hamish2014** [comment]
http://forum.freecadweb.org/viewtopic.php?f=17&t=16591

**Comment by easyw** [comment]
I started to go into FC 0.17 new Part Design and I found a way to let Assembly2 WB to load correctly a Part made with a Visible Body and with sub Parts
http://forum.freecadweb.org/viewtopic.php?f=9&t=17742#p144714

there is a very small diff in the code of the file "importPart.py" of the WB @ line 43

```
   visibleObjects = [ obj for obj in doc.Objects
                       if hasattr(obj,'ViewObject') and obj.ViewObject.isVisible()
                       and hasattr(obj,'Shape') and len(obj.Shape.Faces) > 0 and 'Body' not in obj.Name] # len(obj.Shape.Faces) > 0 to avoid sketches

```
I added only
`and 'Body' not in obj.Name
`

Maurice

**Comment by BPLRFE** [comment]
After some testing i can confirm that this works with FreeCAD 0.16.6706 on Windows 7 - 64 bit (able to import a file saved with version 0.17)
Also tested an confirmed with FreeCAD 0.17.8922 on Windows 7 64-bit.
Code merged into master thanks for contributing.
