### ISSUE TITLE
Changing the licence to LGPL-2.1

### ISSUE THREAD

**Issue by hamish2014** [hamish2014/FreeCAD_assembly2#120]
Hi @fcazorla @f3nix and @easyw 

When i created the FreeCAD_assembly2 I choose a licence which is incompatible with FreeCAD's licence.
Therefore I would like to change the licence to the GNU Lesser General Public License, version 2.1
This gives the FreeCAD team to option to use some of the code should they wish to.

As you are all contributors to assembly2 code belongs to all of us, so i need your permission to re-licence.

Thank you,

**Comment by fcazorla** [comment]
Of course, you have my permission.

Thanks to you, for this useful code :)

**Comment by easyw** [comment]
Hi @hamish2014 
you certainly have my permission...
thank you again for your **great WB!**
Maurice

**Comment by f3nix** [comment]
Hello @hamish2014!

It is ok with me.

Thank you for your great work! :)
Very, very useful and saved me a ton of time!

Cheers,
Mateusz

**Comment by hamish2014** [comment]
Thanks for the kind words everyone :D 
I will re-license now.
