### ISSUE TITLE
typo into git path README file

### ISSUE THREAD

**Issue by davidecaminati** [hamish2014/FreeCAD_assembly2#122]
Hi, 
you have writed into README.md:
....
git clone https://github.com/hamish2014/FreeCAD_drawing_dimensioning.git
.....

but for this repo you need:
git clone https://github.com/hamish2014/FreeCAD_assembly2

thanks.

**Comment by BPLRFE** [comment]
Oops, did not pay enough attention ...
Will correct asap, thanks for reporting

**Comment by BPLRFE** [comment]
Fixed now. Closing issue. Thanks ...
