### ISSUE TITLE
Align icons to FreeCAD guidelines

### ISSUE THREAD

**Issue by agryson** [hamish2014/FreeCAD_assembly2#131]
I recently finished aligning the FreeCAD icons to a unified set of guidelines. [It's been suggested on the forum that i do the same for Assembly2](https://forum.freecadweb.org/viewtopic.php?f=34&t=21420&start=10)
I just want to clear this with the team taking care of this workbench. If you're happy to let me do it, just assign this ticket to me and I'll get to work, if not, simply close the ticket.

**Comment by BPLRFE** [comment]
Hello Alexander.

Thanks for taking care of this. I think a "shape-up" of the icons would be a very good idea.

**Comment by easyw** [comment]
Thx @agryson for taking care of it!
Maurice :smile:

**Comment by agryson** [comment]
Great, expect a PR by end of week.

**Comment by agryson** [comment]
For the curious amongst you:

Before:
![assembly2_before](https://cloud.githubusercontent.com/assets/1445853/24774060/cc5bd53c-1b17-11e7-8a88-6d190abf0c97.png)

After:
![assembly2_preview](https://cloud.githubusercontent.com/assets/1445853/24773985/7fd26974-1b17-11e7-8541-cda38fd6ab7a.png)

**Comment by easyw** [comment]
Oooohh! 😸 
Thx so much! 
Maurice

**Comment by agryson** [comment]
If you like, we don't do it anymore for PRs, github suffices, but if you prefer I can post a topic with a sprite sheet for review.

**Comment by easyw** [comment]
@agryson I posted a comment at the forum before seeing your reply...
https://forum.freecadweb.org/viewtopic.php?f=9&t=17742&p=169102#p169102
I just noticed that the maintainers are more active at the forum than here :smile:

**Comment by agryson** [comment]
No problem, thanks for doing it!
