### ISSUE TITLE
Assembly2 Module does not generate Python Script for each icon clicked in the GUI

### ISSUE THREAD

**Issue by gitansh95** [hamish2014/FreeCAD_assembly2#138]
Hi,

I want to see the Python code that is being executed when I click on an icon from the GUI, to be able to understand the code

Is there a way that  the code that is being executed for the each GUI icon could be printed on the FreeCAD Python Console, like other FreeCAD modules do?

Thanks.

**Comment by ankou29666** [comment]
I've looked into the code and it seems to me pretty clear that the code has never been done to script around it.

**Comment by kbwbe** [comment]
Assembly 2 is now maintained by me in a minimal way, to only keep it still running with fc-0.17 and fc-0.18
More i can not do. So this function will not be implemented. A look at the source files perhaps helps.
