### ISSUE TITLE
Change summary to show compatibility also with 0.17 or just >=0.16

### ISSUE THREAD

**Issue by luzpaz** [hamish2014/FreeCAD_assembly2#140]

**Comment by BPLRFE** [comment]
Readme.MD and Wiki already reflect that.
What summary you are talking about ?

**Comment by luzpaz** [comment]
@BPLRFE on phone now so can't do a proper screenshot. It's in the short description of the repo under the title. It currently reads: 
 > Assembly workbench for FreeCAD v0.16

**Comment by BPLRFE** [comment]
Can only be changed by the owner of the repository (hamish).
I am "only" collaborator.

**Comment by luzpaz** [comment]
@BPLRFE makes sense that you be made co-owner to have these type of permissions since @hamish2014 has moved on... no?

**Comment by hamish2014** [comment]
yip moved on, but updated the description
