### ISSUE TITLE
DeprecationWarning : Use 'TypeId' Instead

### ISSUE THREAD

**Issue by normandc** [hamish2014/FreeCAD_assembly2#142]
Assembly2 apparently uses the attribute "Type" for its custom document objects, but due to conflicts with some sub-classes overriding it and give it a different meaning this attribute was renamed to TypeId in FreeCAD some years ago.

See https://forum.freecadweb.org/viewtopic.php?f=3&t=24423

**Comment by BPLRFE** [comment]
Thanks for mentioning Normand.

**Comment by easyw** [comment]
this issue can be closed :smile:
https://forum.freecadweb.org/viewtopic.php?f=3&t=24423#p192100
it was a deprecated Type attribute in FC code, that has been removed now.
