### ISSUE TITLE
Rotate parts in assembly

### ISSUE THREAD

**Issue by gipsea** [hamish2014/FreeCAD_assembly2#145]
Dear all,

I posted the following thread with example:

https://forum.freecadweb.org/viewtopic.php?f=3&t=24625

I discovered the workfeatures macro and tried to work with it. I could create axis, planes, points in the assembly file. Unfortunately and with some frustration I recognized that these entities are "free floating" in the file and are not correlated to the entities or part used to crete.

My idea (taken from previous experience in ProE) was to create planes on the 2 parts and that allign these entities I was hoping that the constrain will effect the entities and part.

This did not work.

I also created the axis and planes in each part but these can not be used/seen once the part is imported in the assembly

[assieme.zip](https://github.com/hamish2014/FreeCAD_assembly2/files/1346764/assieme.zip)

The above .zip file has a bigger collection of files to be used for the case

Back to my question: How can I turn/allign parts in the Assembly2 workbench?

thanks in advance

**Comment by kbwbe** [comment]
Answer to your main question: (Turn/align parts in Assembly 2 workbench)
Doubleclick the part, which is desired to be rotated/aligned, in the tree view. Some handles on screen appear, which allow to move/rotate the part roughly to desired position. Place the part near to your desired position. Press Escape to leave this modus. After applying constraints, the part should be moved exactly to your desired position.
