### ISSUE TITLE
Assembly2's code documentation

### ISSUE THREAD

**Issue by ankou29666** [hamish2014/FreeCAD_assembly2#146]
Hi

I just would like to know if there is somewhere any documentation that describes the internal workflow of the workbench. I'm especially interested in how the constraints parameters are passed to the solver.

I've tried to get into the code but it's particularly nebulous (understand uncommented)
What I'd like to do is - ideally - create my own assembly workbench with a different human interface but wrapping around Hamish's solver. In order to solve issues I described on #133.

Thanks

**Comment by kbwbe** [comment]
Hello ankou29666,
i had same problems as you to understand exactly how the solver works. This was the reason for me to start a modified version of assembly 2, called A2Plus.
You can find it here: [https://github/kbwe/a2plus](url)
I maintain now Assembly 2 now in a absolute minimal way, just to keep it running for users of fc-0.17/18
If you are interested in assembly solver algorithms, do a post in forum @kbwbe
