### ISSUE TITLE
Being able to define a path in a spreadsheet

### ISSUE THREAD

**Issue by ReneSci** [hamish2014/FreeCAD_assembly2#147]
Thank you for providing FreeCAD and assembly2
Regarding the use of an absolute path in the "source file":
Would it be possible to refer to a spreadsheet to get the full path like this:
https://www.freecadweb.org/wiki/Spreadsheet_Workbench
Instead of having to correct the full path for every single component, with quickly becomes quite cumbersome.
Best regards
Rene'

**Comment by kbwbe** [comment]
Hamish's Assembly 2 is only maintained at absolute minimum to keep it running as is.
So no new functionality will be added.
I opened a new branch "updates-2018-07". If you have a small pull request, i perhaps can merge, if not to big and easy to test.
I am working on a new assembly WB called "A2plus" which you can find here:
[https://github.com/kbwbe/A2plus](url)
It is under active development.
