### ISSUE TITLE
Contraints betwenn to point.

### ISSUE THREAD

**Issue by jbet** [hamish2014/FreeCAD_assembly2#15]
Could you add a constraint of superposition between to points.
I  need to assemble a bridge.

Best regard.

**Comment by jbet** [comment]
I found a solution with sphericalconstraint surface.
I select  sphericalconstraint surface, then two points and the result of Assembly 2 is OK.

BRAVO

**Comment by hamish2014** [comment]
Thanks jbet, keep well.
