### ISSUE TITLE
Constraint within an area

### ISSUE THREAD

**Issue by lanciaux** [hamish2014/FreeCAD_assembly2#17]
Good afternoon,

I really like your Mod - it has helped me a lot (before I was using Draft move tool a lot ... too much ... really too much).

I have had a case where I wanted a pinhole to stay between a closed area : have you some idea to implement this ?

**Comment by lanciaux** [comment]
![assembly2_constraintarea](https://cloud.githubusercontent.com/assets/6277601/7217066/e35110aa-e616-11e4-9093-87e828f027bb.jpeg)

**Comment by hamish2014** [comment]
Hi lanciaux,

Unfortunately, assembly2 does not support limit constraints.

**Comment by lanciaux** [comment]
I do not know you have programmed this mod - I was thinking about using projections on same plane with requiring then to not overlap or having biggest projection UNION smallest projection being still equal biggest projection (in area ?).

Do not worry - as it is, it is already great !
