### ISSUE TITLE
Clicking on constraint to edit it ... make crash

### ISSUE THREAD

**Issue by lanciaux** [hamish2014/FreeCAD_assembly2#18]
Hello,

since addition of sub-assembly import and/or better updating of faces during import, clicking on constraint line in project tree make FreeCAD to crash.

Yours

Ludovic

**Comment by hamish2014** [comment]
Hi Ludovic,

Thank you for reporting the issue.
Could you please provide step by step instructions on how to make the crash occur.

**Comment by lanciaux** [comment]
Hello, I made it a couple of time after writing you. Since I've compiled whole FreeCAD current, it looks to have gone. Anyway, I had suspected for a while this was due to fact I  sometimes do assemblies with object created of the fly.

If it rises again, I will alert you.
