### ISSUE TITLE
svg information

### ISSUE THREAD

**Issue by TomSutrina** [hamish2014/FreeCAD_assembly2#26]
in qcad main view item turned 90 deg from dimensions and center lines properly    

LibreCad still can not read circles or dimensions which is not your problem.  places center lines in all views

will need Geometric Dimensioning & Tolerancing in module  source for special characters
http://www.fontspace.com/micronus/y145m

**Comment by hamish2014** [comment]
Thanks for the feedback Tom Sutrina.
On account of the issue having to do with the drawing dimensioning workbench, I have closed the issue here and moved it to the drawing dimensioning workbench git page, see
https://github.com/hamish2014/FreeCAD_drawing_dimensioning/issues/54
