### ISSUE TITLE
Spherical surface constraint crash

### ISSUE THREAD

**Issue by triplus** [hamish2014/FreeCAD_assembly2#28]
I imported two parts. One Sphere and one Box. I added Spherical surface constraint by selecting Sphere and one edge vertex of Box. Everything works as expected unless i click on added constraint in Tree View and get crash.

**Comment by hamish2014** [comment]
Hi triplus,

Thanks for posting the issue.
I am unable to replicate the crash.
Which version of FreeCAD are you using?
If you are using the devolpment version, please update to latest release and try again.

**Comment by triplus** [comment]
You are correct the problem was on my side. After i deleted FreeCAD .cfg files and updated FreeCAD to latest development release and did a fresh git clone to get FreeCAD_assembly2 WB the crash doesn't happen anymore. I don't know what was the exact reason but it is solved now.

Cheers.

**Comment by hamish2014** [comment]
Great, glad you came right.

**Comment by hamish2014** [comment]
see http://www.freecadweb.org/tracker/view.php?id=2202

**Comment by wwmayer** [comment]
There was a commit from 29. August 2015 which should have fixed this crash. See: https://github.com/FreeCAD/FreeCAD/commit/c3656ad64693105d5d2269142c11b86a18c51be8

**Comment by hamish2014** [comment]
thanks wwmayer.
