### ISSUE TITLE
when I click on constraint the program freecad abort

### ISSUE THREAD

**Issue by abassign** [hamish2014/FreeCAD_assembly2#30]
I try to test Freecad Linux (Ubuntu) version 5238, I link two object by Assembly 2, but when I click on constraint the program go to abort whit this log:

[code]
....
Log: Active view is Unnamed : 1[*] (at 0x3fa5370)
Log: Active document is Senza_nome (at 0x413a290)
Log: Sel : Clear selection
Log: Active view is Senza nome : 1[*] (at 0x3fa5370)
Log: Sel : Add Selection "Senza_nome.Sketch.Edge2(23.000000,-6.277217,0.007000)"
Log: Sel : Clear selection
Err: *** Abort *** an exception was raised, but no catch was found.Err: 
Err: 	... The exception is:Err: SIGSEGV 'segmentation violation' detected. Address 0Err: 
[/code]

Is it possible to resolve this problem ?

**Comment by hamish2014** [comment]
Hi abassign,

I have not encountered the problem described above.
Hmmm, I also use Freecad Linux (Ubuntu) version 5238, but do not encounter the error mentioned.
Tell me:

* is error specific to the assembly2 workbench, or do the other workbenches such are part design crash as well?
* where did you intall the assembly2 workbench from, git, ppa?
* have you tested your system's NumPy's installation?
