### ISSUE TITLE
Cannot update parts in assembly

### ISSUE THREAD

**Issue by f3nix** [hamish2014/FreeCAD_assembly2#39]
Hi,
when trying to update parts imported into assembly I get:

```
Running the Python command 'updateImportedPartsCommand' failed:
Traceback (most recent call last):
  File "/home/f3nix/.FreeCAD/Mod/FreeCAD_assembly2/importPart.py", line 187, in Activated
    importPart( obj.sourceFile, obj.Name )
  File "/home/f3nix/.FreeCAD/Mod/FreeCAD_assembly2/importPart.py", line 61, in importPart
    importUpdateConstraintSubobjects( FreeCAD.ActiveDocument, obj, obj_to_copy )
  File "/home/f3nix/.FreeCAD/Mod/FreeCAD_assembly2/importPart.py", line 485, in importUpdateConstraintSubobjects
    newObjSubElements = classifySubElements( newObject )
  File "/home/f3nix/.FreeCAD/Mod/FreeCAD_assembly2/importPart.py", line 432, in classifySubElements
    catergory = classifySubElement( obj, subElementName )
  File "/home/f3nix/.FreeCAD/Mod/FreeCAD_assembly2/importPart.py", line 407, in classifySubElement
    elif CircularEdgeSelected( selection ):
  File "/home/f3nix/.FreeCAD/Mod/FreeCAD_assembly2/assembly2lib.py", line 268, in CircularEdgeSelected
    if hasattr( edge.Curve, 'Radius' ):

undefined curve type
```

Any idea what is going on? It used to work just fine.

Cheers,
Mateusz

**Comment by f3nix** [comment]
Hi,
here are the files that are problematic:
https://freeshell.de/~f3nix/freecad/assembly_bug.7z

The other assembly updates just fine.

Cheers,
Mateusz

**Comment by paul18fr** [comment]
Hi Mateusz

Well I tested it (on my Ubuntu with the latest released Assembly2 module) and It seems (but maybe I'm mistaken - some parts may be missing) that it goes right as you can see in the 2 screenshoots (no particular error message even in the python console)

NB: your designs are quite impressive and I'm notocing some good ideas in your file structure ...

Paul

![assembly1](https://cloud.githubusercontent.com/assets/13578030/9417626/2fa31306-484e-11e5-8d3e-0b9527214986.png)

![assembly2](https://cloud.githubusercontent.com/assets/13578030/9417628/35ba6e74-484e-11e5-8de6-bb3a64f2343f.png)

**Comment by f3nix** [comment]
Hi Paul,
the problem is not in the file loading. It opens without problems for me too.

Here is the thing. I have updated the colors of screws in the appropriate files (fasteners directory). And then when I click on "Update parts imported into assembly" (second icon) I get the aforementioned error message. It shows in the report view (View->Views->Report view).

The result I wanted to achieve was changing the color of the screws from green to something else...

![image](https://cloud.githubusercontent.com/assets/72836/9418858/56f8ca5a-4857-11e5-988c-8d59c93d5d6e.png)

Cheers,
Mateusz

P.S. These are not my designs. It is an open source 3D printer. Lulzbot TAZ 5. I have just ported some parts from pdf and solidworks.

**Comment by hamish2014** [comment]
Hi,

The error occurs because one of the edges in a faster part (M8x35 or something) does not have a Curve attribute.
Which is problematic because when i wrote the edge classification code, I assumed all edge objects would have the Curve attribute.

Anyway, patched it.
Please try it out and see if your issues is resolved.

**Comment by hamish2014** [comment]
Ps, if you aren't already try out the the 'Bolt Multiple Circular Edges' command (next to animate assembly icon) which i added on Wed/Thursday.
The command should make things a little quicker...

**Comment by f3nix** [comment]
Hi Hamish2014,
thank You. This have solved the problem for me and the assembly files updated without problems. :)

Yes. I have played around with 'Bolt Multiple Circular Edges'. It's a real time saver. Thanks again! :) :+1: 

Cheers,
Mateusz
