### ISSUE TITLE
Constraint surface with surface not possible

### ISSUE THREAD

**Issue by corvusd** [hamish2014/FreeCAD_assembly2#5]
First of all thank you for you great work.

The actual state of the module is great.

If possible implement, as improved critical, constraint between faces of the body´s?

I have used these objects to my tests: https://drive.google.com/file/d/0B0mSen1pNtD4aEFXVENhb2dCd1U/view?usp=sharing

The test consist in position the object like this example: http://www.iearobotics.com/wiki/images/thumb/e/e7/T39-ej1-soporte-aquaris-5-7-3.png/300px-T39-ej1-soporte-aquaris-5-7-3.png

If you want or need that I help you to improve your project. Only tell me something via email: david.gamiz@gmail.com

Greetings,

David Gámiz Jiménez

**Comment by hamish2014** [comment]
Hi David, 

Thank you for registering the issue.
I have downloaded the files, and will see what i can do.

**Comment by corvusd** [comment]
Thanks again.

For anything you need, here I am.

I will continue testing your module. :)

**Comment by hamish2014** [comment]
Hi David,

Okay, so the difficulties you encountered when trying to assemble the phone+stand originated from lack of flat surfaces.
Almost all the surfaces on the phone are curved, very slightly.
To overcome this, i ended up adding functionality to the assembly 2 workbench.
Functionality added:
 - plane-vertex constraints
 - edge-edge angle constraints


![pruebas](https://cloud.githubusercontent.com/assets/7496850/5939446/6f0b6162-a70c-11e4-8bbc-6c93490819d9.png)

**Comment by corvusd** [comment]
PLAS PLAS! applauses! :D :D

Took more than eight years in the free software community.

And I never cease to amaze me. Rejoice in the great people there!

Thank You. I continue by testing your module. And bringing everything I can.

A strong greeting! : D

**Comment by hamish2014** [comment]
Pleasure, keep well.
