### ISSUE TITLE
use object label instead of name in data tab of constraint

### ISSUE THREAD

**Issue by QiangF** [hamish2014/FreeCAD_assembly2#58]
Hello everyone,
I changed the imported object labels to names that are easy to identify. However in the data tab of the constraint relation, the object are still identified by the name given by the system when the object is imported. The drawback is I can't see which object the current constraint is acting on anymore. 
Thank you!

**Comment by hamish2014** [comment]
Ultimately what is needed for the constraint to put under the objects they are applied to.
See https://github.com/hamish2014/FreeCAD_assembly2/issues/36
