### ISSUE TITLE
Plain constraint offset not working

### ISSUE THREAD

**Issue by QiangF** [hamish2014/FreeCAD_assembly2#60]
Hello everyone,
I tried to change the offset value in the data tab of a plain constraint, but it has not effect.
My software versions are
OS: Debian GNU/Linux 8.0 (jessie)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.16.5632 (Git)
Build type: Release
Branch: master
Hash: 8c38e253773088d76e8e5e2348afd9b42a7073b8
Python version: 2.7.9
Qt version: 4.8.6
Coin version: 4.0.0a
OCC version: 6.7.0

**Comment by hamish2014** [comment]
Repeat of https://github.com/hamish2014/FreeCAD_assembly2/issues/54 ?

**Comment by QiangF** [comment]
Exactly, thank you!
