### ISSUE TITLE
Angle adjust for circular constrains

### ISSUE THREAD

**Issue by Rafa350** [hamish2014/FreeCAD_assembly2#75]
Interesting option, for example, to mount a shaft with a rod.

**Comment by hamish2014** [comment]
Hi,

My thoughts are as follows

For non-purely revolved object, use the non-revolved feature to align the object.
i.e. for a shaft with a keyway slot, use the keyway to specify the shafts orientation

for purely revolved objects, rotation orientation is immaterial, and just lock the circular constraint
