### ISSUE TITLE
Cannot find icon: partsList.svg

### ISSUE THREAD

**Issue by wood-galaxy** [hamish2014/FreeCAD_assembly2#8]
Hi hamish,
When I load Assembly 2 WB i get this in report view :
Cannot find icon: /home/jo/.FreeCAD/Mod/Dimensioning/partsList.svg
In fact there is the file in FreeCAD_assembly2 folder but not in Dimensioning folder.

**Comment by hamish2014** [comment]
stange; 
Please pull the latest version, and see if the patch contained, fixes things

**Comment by wood-galaxy** [comment]
Yep it's really strange,
I don't see why the path change to Dimensioning instead of Assembly2.
>>> import os
>>> file = '/home/jo/.FreeCAD/Mod/FreeCAD_assembly2/assembly2lib.py'
>>> os.path.dirname(file)
'/home/jo/.FreeCAD/Mod/FreeCAD_assembly2'

Anyway, I delete all pyc file and now it's working WITH and WITHOUT the path. Very sorry for the noise.
Excellent work Hamish and thank you.

**Comment by hamish2014** [comment]
Pleasure, glad it is working again.
