### ISSUE TITLE
Can't update old assembly files

### ISSUE THREAD

**Issue by f3nix** [hamish2014/FreeCAD_assembly2#81]
Hi,
I have a few assemblies created in earlier versions of Assembly2.

I can't update the parts in them.

The error message is:

```
Running the Python command 'updateImportedPartsCommand' failed:
Traceback (most recent call last):
  File "/home/f3nix/.FreeCAD/Mod/FreeCAD_assembly2/importPart.py", line 248, in Activated
    obj.ViewObject.Proxy.mirror_name = create_constraint_mirror(  obj, obj.ViewObject.Proxy.iconPath )

'int' object has no attribute 'iconPath'
```

These assemblies were created before introduction of constraints icons. Is there an easy way to fix it?

Cheers,
Mateusz

**Comment by hamish2014** [comment]
Hi Mateusz,

What needs to be done is to loop over all the old constraint objects and assign ConstraintViewProviderProxy's to their ViewObject proxies.
See the code added in patch 7c8fa38 

Doing this work yourself should not be necessary with latest patch.
Simply load the old assembly, and press the solve assembly button.
This will end up calling updateObjectProperties function, which (with the latest patch) will add ConstraintViewProviderProxy to old constraint objects.

Kind Regards,

**Comment by f3nix** [comment]
Hi,
Thanks for coding it! I just got some time to test this.

I have spotted one problem. After clicking solve it seems that the update did not work. Mirrors are created but the old constraints look the same (default icon). I have to save, close and reload the document for changes to take effect. This is on latest dev branch.

Any idea what is going on?

Thanks again! :)

Cheers,
Mateusz

**Comment by hamish2014** [comment]
Hi,

On my side I also have to save, and reopen the file for the changes to take effect.
Also don't know why :)

Anyway ...

**Comment by f3nix** [comment]
Hi,
after more testing I think this issue is not solved completly.

E.g.
I'm trying to convert my old assembly. It can be downloaded here: http://forum.freecadweb.org/viewtopic.php?f=24&t=13374

In this assembly parts and constraints were grouped.

This is how it looks in previous assembly (f1e52167d39898832f2fdaef8d60726c4969cda7):
![image](https://cloud.githubusercontent.com/assets/72836/12005359/61493c6c-aba1-11e5-97d1-d9cc3d6fd34d.png)

This is how it looks in latest assembly (after solving and saving the file: 7d71abaa2e24cbb69df050b0029fa72b412b183c)
![image](https://cloud.githubusercontent.com/assets/72836/12005392/b8b6d83c-aba2-11e5-9007-118d2a8fe579.png)

And this is how it looks during loading in latest assembly:
![image](https://cloud.githubusercontent.com/assets/72836/12005396/192b40a4-aba3-11e5-9abe-3249a1426e68.png)

It looks like the objects were not "physically" moved. But the grouping is updated during loading. It introduces a bug.
After loading the assembly and deleting e.g. the "Constrains" group (which seems to be empy) the assembly is no longer solvable.

Hitting solve gives:
```
UNABLE TO SOLVE CONSTRAINTS! info:Traceback (most recent call last):
  File "/home/f3nix/.FreeCAD/Mod/FreeCAD_assembly2/assembly2solver.py", line 106, in solveConstraints
    if constraintObj.lockRotation: constraintSystem =  LockRelativeAxialRotationUnion(constraintSystem,  *cArgs, constraintValue = 0)
  File "/home/f3nix/.FreeCAD/Mod/FreeCAD_assembly2/constraintSystems.py", line 75, in __init__
    self.init2()
  File "/home/f3nix/.FreeCAD/Mod/FreeCAD_assembly2/constraintSystems.py", line 846, in init2
    assert isinstance(sys.sys2, FreeObjectSystem)
AssertionError
```

Cheers,
Mateusz
